# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Argv
version:      1.25
version_from: Argv.pm
installdirs:  site
requires:
    Getopt::Long:                  2.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
