#!/usr/bin/perl -w

use strict;
use Sudo;
BEGIN {
  delete @ENV{qw(IFS CDPATH PATH ENV BASH_ENV)};
}

# This is meant to be suid enabled
# This is the version using sudo. There is an alternative version using ssh.

my $fsc ='/usr/local/bin/fixsrccont';

my $rc = 0;
my %batch;
for (@ARGV) {
  push @{$batch{$1}}, $2 if /^(\w+?):(.*)$/;
}
for my $owner (keys %batch) {
  my $arg = join '@@', @{$batch{$owner}}; # split on whitespace...
  if ((getpwuid($<))[0] eq $owner) {
    $rc = system($fsc, $arg);
  } else {
    my $su = Sudo->new({
      sudo => '/usr/bin/sudo',
      username => $owner,
      program => $fsc,
      program_args => $arg
    });
    my $res = $su->sudo_run();
    if (!$res->{rc}) {
      $rc = 1;
      print STDERR $res->{stderr}, "\n";
    }
    print STDOUT $res->{stdout}, "\n";
  }
}
exit $rc;
